### PR TITLE
Added support for multi-native librararies aka multi-artifacts

### PR DESCRIPTION
**Pull request by lpalonek**
Added multi-artifact support. I've tested it with tess-two( https://github.com/rmtheis/tess-two) and it works fine.

### CODE REVIEW

**Comment by mosabua** [comment]
Looks good to me. wdyt @johanlindquist ?

**Comment by johanlindquist** [comment]
Looks good to me too - sample project would be nice of course :)

**Comment by lpalonek** [comment]
I can prepare sample project in next week.

**Comment by mosabua** [comment]
Great... just add it to this pull request and run it as another IT test.

**Comment by johanlindquist** [comment]
hi @lpalonek - quick question about this one - is this meant to solve many artifacts (modules) resulting from a single build for an architecture or many architectures built in a single invoke of NDK build?

I have run into some issues with multiple architectures and when looking at the code somewhat closer, I am wondering if this is actually working as intended.

From the tess-two project, what artifacts do you expect to be attached?

Thanks,

johan

**Pull request merged**
